### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Hamdan85** [iliojunior/vuetify-credit-card#5]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                     

 error  in ./node_modules/vuetify-credit-card/src/components/Card.vue?vue&type=style&index=0&lang=stylus&

Syntax Error: SyntaxError

(24:8) Unknown word

  22 |         shape()
  23 |         linear-gradient($highlight-color, lighten($highlight-color, 20%), $highlight-color)
> 24 |         height: $size
     |        ^
  25 |         width: $size
  26 |         border-radius: ($size / 2)

**Comment by JChiquin** [comment]
``` 
error  in ./node_modules/vuetify-credit-card/src/components/Card.vue?vue&type=style&index=0&lang=stylus&

Syntax Error: SyntaxError

(142:3) Unknown word

  140 |   display: block;
  141 | #ff8533
> 142 |   height: 50px;
      |   ^
  143 |   width: 50px;
  144 |   border-radius: 25px;

```

**Comment by KaziSadmanAhmed** [comment]
Fixed. Please update to the latest release.
